### ISSUE TITLE
Cannot access dashboard after login 

### ISSUE THREAD

**Issue by mariuskimmina** [hugsy/ctfpad#52]
Hey, 

I'm trying to setup the ctfpad on an ubuntu 20.04 server, after adjusting the docker-compose.yml, I started the server, created a team, created a member and once I try to login I get the following error:

```
ctfpad_1      | Internal Server Error: /dashboard/
ctfpad_1      | Traceback (most recent call last):
ctfpad_1      |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
ctfpad_1      |     response = get_response(request)
ctfpad_1      |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
ctfpad_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
ctfpad_1      |   File "/code/ctfpad/decorators.py", line 31, in wrapper_func
ctfpad_1      |     return view_func(request, *args, **kwargs)
ctfpad_1      |   File "/code/ctfpad/views/__init__.py", line 56, in dashboard
ctfpad_1      |     member = user.member
ctfpad_1      |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
ctfpad_1      |     return func(self._wrapped, *args)
ctfpad_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
ctfpad_1      |     raise self.RelatedObjectDoesNotExist(
ctfpad_1      | django.contrib.auth.models.User.member.RelatedObjectDoesNotExist: User has no member.
```

Or as represented in the web view:
```
Environment:


Request Method: GET
Request URL: http://xxx.xxx.xxx.xxx:8000/dashboard/

Django Version: 3.2.3
Python Version: 3.9.5
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django.contrib.sites',
 'model_utils',
 'ctfpad']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/ctfpad/decorators.py", line 31, in wrapper_func
    return view_func(request, *args, **kwargs)
  File "/code/ctfpad/views/__init__.py", line 56, in dashboard
    member = user.member
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 421, in __get__
    raise self.RelatedObjectDoesNotExist(

Exception Type: RelatedObjectDoesNotExist at /dashboard/
Exception Value: User has no member.
```

Any Ideas what I could be doing wrong?

**Comment by hugsy** [comment]
Hi @Mindslave 

The error line `django.contrib.auth.models.User.member.RelatedObjectDoesNotExist: User has no member.` seems to point to a Django migration issue.

Can you : 
1. try to rebuild the container, making sure the `python manage migrate` is correctly executed?
2. if still not working, dump here the commands you typed and the `docker-compose.yml` so we can try to reproduce the issue?

Thanks!

**Comment by mariuskimmina** [comment]
During startup (docker-compose) it said that:

```
ctfpad_1      | DB setup: makemigrations...
hedgedoc_1    | No migrations were executed, database schema was already up to date.
```

and also:

```
ctfpad_1      | Operations to perform:
ctfpad_1      |   Apply all migrations: auth, contenttypes, ctfpad, sessions, sites
ctfpad_1      | Running migrations:
ctfpad_1      |   No migrations to apply.
```

But it must have definitely been a problem of my setup, I just redid the whole installation and now it acctually works without any problems.

**Comment by hugsy** [comment]
Awesome, closing the issue then! Thanks
