### ISSUE TITLE
Container not starting due to missmatching variable name

### ISSUE THREAD

**Issue by DocSnibble** [hugsy/ctfpad#98]
**Describe the bug**
Variable name in .env file is wrong which leeds to a raise of ValidationError.
In helpers.py line 92 you check for url = settings.HEDGEDOC_URL.rstrip("/").lower()
In .env file name of URL is either CTFHUB_HEDGEDOC_PUBLIC_URL or CTFHUB_HEDGEDOC_PRIVATE_URL.
If you replace  CTFHUB_HEDGEDOC_PUBLIC_URL with CTFHUB_HEDGEDOC_URL everything works.

**To Reproduce**
1. Follow instructions to setup new instance
2. Chance important variables in .env file
3. Execute docker compose up --build
4. Error shows up in logs

**Additional context**

```text
ctfhub-ctfhub-1    | Traceback (most recent call last):
ctfhub-ctfhub-1    |   File "/code/manage.py", line 22, in <module>
ctfhub-ctfhub-1    |     main()
ctfhub-ctfhub-1    |   File "/code/manage.py", line 18, in main
ctfhub-ctfhub-1    |     execute_from_command_line(sys.argv)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
ctfhub-ctfhub-1    |     utility.execute()
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
ctfhub-ctfhub-1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
ctfhub-ctfhub-1    |     self.execute(*args, **cmd_options)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 453, in execute
ctfhub-ctfhub-1    |     self.check()
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
ctfhub-ctfhub-1    |     all_issues = checks.run_checks(
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
ctfhub-ctfhub-1    |     new_errors = check(app_configs=app_configs, databases=databases)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
ctfhub-ctfhub-1    |     return check_resolver(resolver)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
ctfhub-ctfhub-1    |     return check_method()
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
ctfhub-ctfhub-1    |     for pattern in self.url_patterns:
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
ctfhub-ctfhub-1    |     res = instance.__dict__[self.name] = self.func(instance)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
ctfhub-ctfhub-1    |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
ctfhub-ctfhub-1    |     res = instance.__dict__[self.name] = self.func(instance)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
ctfhub-ctfhub-1    |     return import_module(self.urlconf_name)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
ctfhub-ctfhub-1    |     return _bootstrap._gcd_import(name[level:], package, level)
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ctfhub-ctfhub-1    |   File "/code/ctfhub_project/urls.py", line 20, in <module>
ctfhub-ctfhub-1    |     path("", include("ctfhub.urls")),
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
ctfhub-ctfhub-1    |     urlconf_module = import_module(urlconf_module)
ctfhub-ctfhub-1    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
ctfhub-ctfhub-1    |     return _bootstrap._gcd_import(name[level:], package, level)
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ctfhub-ctfhub-1    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ctfhub-ctfhub-1    |   File "/code/ctfhub/urls.py", line 7, in <module>
ctfhub-ctfhub-1    |     from ctfhub import views
ctfhub-ctfhub-1    |   File "/code/ctfhub/views/__init__.py", line 14, in <module>
ctfhub-ctfhub-1    |     from . import (
ctfhub-ctfhub-1    |   File "/code/ctfhub/views/ctfs.py", line 133, in <module>
ctfhub-ctfhub-1    |     class CtfDetailView(LoginRequiredMixin, DetailView):
ctfhub-ctfhub-1    |   File "/code/ctfhub/views/ctfs.py", line 141, in CtfDetailView
ctfhub-ctfhub-1    |     "hedgedoc_url": helpers.HedgeDoc(("anonymous", "")).public_url,
ctfhub-ctfhub-1    |   File "/code/ctfhub/helpers.py", line 111, in public_url
ctfhub-ctfhub-1    |     return self.url
ctfhub-ctfhub-1    |   File "/code/ctfhub/helpers.py", line 94, in url
ctfhub-ctfhub-1    |     raise ValidationError(f"Invalid URL protocol for {url}")
ctfhub-ctfhub-1    | django.core.exceptions.ValidationError: ['Invalid URL protocol for ']
```

**Comment by hugsy** [comment]
Thanks for letting me know. The PR fixing this will be merged soon.
